fix undefined behavior with va_arg on 16-bit value
macOS produces this warning:
lzw.c:120:21: error:
    second argument to 'va_arg' is of promotable type 'mode_t' (aka 'unsigned short');
    this va_arg has undefined behavior because arguments will be promoted to 'int' [-Werror,-Wvarargs]
        mode = va_arg(ap, mode_t);
                          ^~~~~~